/** Stable class names shared by the renderers and stylesheet. */
export const styles = {
  board: 'flapkit-board',
  boardContent: 'flapkit-board-content',
  standaloneGrid: 'flapkit-standalone-grid',
  outerRim: 'flapkit-outer-rim',
  innerRim: 'flapkit-inner-rim',
  boardSheen: 'flapkit-board-sheen',
  boardGrain: 'flapkit-board-grain',
  srOnly: 'flapkit-sr-only',
  boardHeader: 'flapkit-board-header',
  boardColumnLabels: 'flapkit-board-column-labels',
  boardColumnLabel: 'flapkit-board-column-label',
  grid: 'flapkit-grid',
  motionCanvas: 'flapkit-motion-canvas',
  staticMotionCanvas: 'flapkit-static-motion-canvas',
  departureRow: 'flapkit-departure-row',
  departureGroup: 'flapkit-departure-group',
  departureGroupScaleContext: 'flapkit-departure-group-scale-context',
  departureGroupGrid: 'flapkit-departure-group-grid',
  cassette: 'flapkit-cassette',
  compactCassette: 'flapkit-compact-cassette',
  cell: 'flapkit-cell',
  compactCell: 'flapkit-compact-cell',
  cellScene: 'flapkit-cell-scene',
  cavityBackPlane: 'flapkit-cavity-back-plane',
  cavityWall: 'flapkit-cavity-wall',
  cavityWallTop: 'flapkit-cavity-wall-top',
  cavityWallRight: 'flapkit-cavity-wall-right',
  cavityWallBottom: 'flapkit-cavity-wall-bottom',
  cavityWallLeft: 'flapkit-cavity-wall-left',
  faceLayer: 'flapkit-face-layer',
  outgoingLower: 'flapkit-outgoing-lower',
  arrivingUpper: 'flapkit-arriving-upper',
  compactGlyphCarrier: 'flapkit-compact-glyph-carrier',
  compactWideGlyphCarrier: 'flapkit-compact-wide-glyph-carrier',
  compactUpper: 'flapkit-compact-upper',
  compactLower: 'flapkit-compact-lower',
  compactStaticFace: 'flapkit-compact-static-face',
  compactStaticTop: 'flapkit-compact-static-top',
  compactStaticBottom: 'flapkit-compact-static-bottom',
  compactMovingVane: 'flapkit-compact-moving-vane',
  compactMovingVaneFace: 'flapkit-compact-moving-vane-face',
  compactMovingStack: 'flapkit-compact-moving-stack',
  movingVane: 'flapkit-moving-vane',
  movingVaneFace: 'flapkit-moving-vane-face',
  movingVaneFront: 'flapkit-moving-vane-front',
  movingVaneBack: 'flapkit-moving-vane-back',
  movingVaneSide: 'flapkit-moving-vane-side',
  movingVaneSideLeft: 'flapkit-moving-vane-side-left',
  movingVaneSideRight: 'flapkit-moving-vane-side-right',
  cassetteCover: 'flapkit-cassette-cover',
  cassetteCoverTop: 'flapkit-cassette-cover-top',
  cassetteCoverRight: 'flapkit-cassette-cover-right',
  cassetteCoverBottom: 'flapkit-cassette-cover-bottom',
  cassetteCoverLeft: 'flapkit-cassette-cover-left',
  face: 'flapkit-face',
  topFace: 'flapkit-top-face',
  bottomFace: 'flapkit-bottom-face',
  glyph: 'flapkit-glyph',
  wideGlyphCarrier: 'flapkit-wide-glyph-carrier',
  wideGlyphPart: 'flapkit-wide-glyph-part',
  compactWideGlyphPart: 'flapkit-compact-wide-glyph-part',
  wideGlyphPartLeft: 'flapkit-wide-glyph-part-left',
  wideGlyphPartRight: 'flapkit-wide-glyph-part-right',
  glyphHalf: 'flapkit-glyph-half',
  topGlyphHalf: 'flapkit-top-glyph-half',
  bottomGlyphHalf: 'flapkit-bottom-glyph-half',
  glyphFarLeft: 'flapkit-glyph-far-left',
  glyphLeft: 'flapkit-glyph-left',
  glyphCenter: 'flapkit-glyph-center',
  glyphSoftRight: 'flapkit-glyph-soft-right',
  glyphRight: 'flapkit-glyph-right',
  seam: 'flapkit-seam',
  axle: 'flapkit-axle',
  axleLeft: 'flapkit-axle-left',
  axleRight: 'flapkit-axle-right',
  compactHardware: 'flapkit-compact-hardware',
  wideRetainer: 'flapkit-wide-retainer',
  wideRetainerOuterLeft: 'flapkit-wide-retainer-outer-left',
  wideRetainerInnerLeft: 'flapkit-wide-retainer-inner-left',
  wideRetainerInnerRight: 'flapkit-wide-retainer-inner-right',
  wideRetainerOuterRight: 'flapkit-wide-retainer-outer-right',
  spareLeafPack: 'flapkit-spare-leaf-pack',
  spareLeafPlate: 'flapkit-spare-leaf-plate',
  cassetteBezel: 'flapkit-cassette-bezel',
} as const

export const glyphOffsets = [
  styles.glyphLeft,
  styles.glyphCenter,
  styles.glyphRight,
  styles.glyphFarLeft,
  styles.glyphCenter,
  styles.glyphSoftRight,
] as const

export function classProps(...classes: Array<string | false | null | undefined>) {
  return { className: classes.filter(Boolean).join(' ') }
}
