export {
  SplitFlapBoard,
  SplitFlapGrid,
  type SplitFlapBoardProps,
  type SplitFlapGridProps,
} from './split-flap.board'
export {
  Board,
  Cell,
  Group,
  Header,
  Root,
  Row,
  WideCell,
  type BoardProps,
  type CellProps,
  type GroupProps,
  type HeaderProps,
  type MotionAdapter,
  type RootProps,
  type RowProps,
  type Variant,
  type WideCellProps,
} from './flapkit'
export {
  createSplitFlapDeck,
  splitFlapGraphemes,
  splitFlapCharacters,
  splitFlapNumericCharacters,
  splitFlapPunctuationCharacters,
  splitFlapVariants,
  type SplitFlapCassetteSpan,
  type SplitFlapColumn,
  type SplitFlapDeck,
  type SplitFlapPosition,
  type SplitFlapRow,
  type SplitFlapSequence,
  type SplitFlapSource,
  type SplitFlapVariant,
  type SplitFlapValue,
} from './split-flap.source'
export {
  defaultSplitFlapMaterial,
  splitFlapMaterialStyle,
  type SplitFlapMaterial,
  type SplitFlapStyle,
} from './split-flap.material'
