import * as stylex from '@stylexjs/stylex'
import { splitFlapLook } from './split-flap-look.stylex'

export const styles = stylex.create({
  board: {
    position: 'relative',
    zIndex: 1,
    boxSizing: 'border-box',
    margin: 0,
    width: 'max-content',
    overflow: 'hidden',
    borderRadius: '0.98px',
    backgroundColor: splitFlapLook.boardBackgroundColor,
    backgroundImage: splitFlapLook.boardBackgroundImage,
    boxShadow: splitFlapLook.boardShadow,
  },
  boardContent: {
    position: 'relative',
    display: 'grid',
    boxSizing: 'border-box',
    padding: `${splitFlapLook.frameTop} ${splitFlapLook.frameRight} ${splitFlapLook.frameBottom} ${splitFlapLook.frameLeft}`,
    containerType: 'inline-size',
  },
  standaloneGrid: {
    position: 'relative',
    zIndex: 1,
    margin: 0,
    width: 'max-content',
    overflow: 'clip',
    overflowClipMargin: '1px',
    isolation: 'isolate',
    containerType: 'inline-size',
  },
  outerRim: {
    position: 'absolute',
    zIndex: 2,
    inset: '5.08px',
    borderRadius: '0.49px',
    boxShadow:
      '0 0 0 1.31px rgba(8, 9, 7, 0.74), 0 1.15px 0 rgba(214, 208, 174, 0.018), 0 0 0 0.66px rgba(197, 195, 166, 0.025) inset, 0 -1.48px 2.62px rgba(0, 0, 0, 0.42) inset',
    pointerEvents: 'none',
  },
  innerRim: {
    position: 'absolute',
    zIndex: 2,
    top: `calc(${splitFlapLook.frameTop} + var(--split-flap-header-height) - 1.07px)`,
    right: `calc(${splitFlapLook.frameRight} - 5px)`,
    bottom: `calc(${splitFlapLook.frameBottom} - 5.49px)`,
    left: `calc(${splitFlapLook.frameLeft} - 5.41px)`,
    borderRadius: 0,
    boxShadow:
      '0 0 0 1.48px rgba(9, 10, 8, 0.78), 0 -0.82px 0 rgba(217, 211, 177, 0.025), 0 1.15px 0 rgba(0, 0, 0, 0.62)',
    pointerEvents: 'none',
  },
  boardSheen: {
    position: 'absolute',
    zIndex: 4,
    inset: 0,
    backgroundImage:
      'radial-gradient(ellipse 48% 19% at 31% 16%, rgba(211, 205, 169, 0.025), transparent 76%), radial-gradient(ellipse 24% 62% at 76% 54%, rgba(0, 0, 0, 0.12), transparent 78%), repeating-linear-gradient(89deg, transparent 0 5.7cqw, rgba(221, 215, 180, 0.006) 5.76cqw 5.83cqw, transparent 5.9cqw 11.8cqw)',
    pointerEvents: 'none',
  },
  boardGrain: {
    position: 'absolute',
    zIndex: 5,
    inset: 0,
    width: '100%',
    height: '100%',
    opacity: 0.32,
    mixBlendMode: 'overlay',
    pointerEvents: 'none',
  },
  boardHeader: {
    position: 'relative',
    zIndex: 3,
    display: 'grid',
    boxSizing: 'border-box',
    height: 'var(--split-flap-header-height)',
    gridTemplateRows: 'max-content 1fr',
    color: '#a6a58f',
    fontFamily: splitFlapLook.labelFontFamily,
    textShadow: '0 0.65px 0 rgba(0, 0, 0, 0.82)',
    textTransform: 'uppercase',
    pointerEvents: 'none',
  },
  boardTitleLine: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    minWidth: 0,
  },
  boardTitle: {
    color: '#d0cdb3',
    fontSize: '13.1px',
    fontWeight: 650,
    letterSpacing: '0.125em',
    lineHeight: 1,
  },
  boardMeta: {
    color: '#858574',
    fontSize: '7.4px',
    fontWeight: 550,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '0.11em',
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  boardColumnLabels: {
    display: 'grid',
    alignSelf: 'end',
    minWidth: 0,
    paddingBottom: '7.8px',
    color: '#92917d',
    fontSize: '7.6px',
    fontWeight: 570,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '0.075em',
    lineHeight: 1,
  },
  boardColumnLabel: {
    overflow: 'hidden',
    minWidth: 0,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  grid: {
    position: 'relative',
    zIndex: 3,
    display: 'grid',
    width: 'max-content',
    backgroundColor: splitFlapLook.gridBackgroundColor,
    backgroundImage: splitFlapLook.gridBackgroundImage,
    boxShadow: splitFlapLook.gridShadow,
  },
  motionCanvas: {
    position: 'absolute',
    zIndex: 5,
    inset: 0,
    display: 'block',
    width: '100%',
    height: '100%',
    pointerEvents: 'none',
  },
  staticMotionCanvas: {
    zIndex: 4,
  },
  departureRow: {
    position: 'relative',
    display: 'grid',
    width: 'max-content',
    gridTemplateColumns: '5fr 6fr 11fr 3fr 11fr',
    columnGap: '0.8cqw',
    backgroundColor: splitFlapLook.rowBackgroundColor,
    backgroundImage: splitFlapLook.rowBackgroundImage,
    boxShadow: splitFlapLook.rowShadow,
  },
  departureField: {
    position: 'relative',
    minWidth: 0,
  },
  departureFieldScaleContext: {
    position: 'relative',
    containerType: 'inline-size',
    pointerEvents: 'none',
  },
  departureFieldGrid: {
    display: 'grid',
    height: 'max-content',
    gridTemplateColumns: 'repeat(11, minmax(0, 1fr))',
    columnGap: '0.28cqw',
    pointerEvents: 'auto',
  },
  cassette: {
    position: 'relative',
    display: 'block',
    width: '100%',
    height: splitFlapLook.cellHeight,
    minWidth: 0,
    overflow: 'visible',
    borderRadius: splitFlapLook.cassetteRadius,
    backgroundColor: splitFlapLook.cassetteBackgroundColor,
    backgroundImage: splitFlapLook.cassetteBackgroundImage,
    boxShadow: splitFlapLook.cassetteShadow,
  },
  compactCassette: {
    '::before': {
      position: 'absolute',
      zIndex: 8,
      inset: 0,
      content: '',
      backgroundImage: splitFlapLook.compactHardwareBackground,
      backgroundPosition: splitFlapLook.compactHardwarePosition,
      backgroundRepeat: 'no-repeat',
      backgroundSize: splitFlapLook.compactHardwareSize,
      pointerEvents: 'none',
    },
    '::after': {
      position: 'absolute',
      zIndex: 7,
      inset: 0,
      content: '',
      backgroundImage: splitFlapLook.compactCoverDetail,
      pointerEvents: 'none',
    },
  },
  wideCompactCassette: {
    '::before': {
      backgroundImage: 'none',
    },
  },
  cell: {
    position: 'absolute',
    top: splitFlapLook.cavityTop,
    right: splitFlapLook.cavityRight,
    bottom: splitFlapLook.cavityBottom,
    left: splitFlapLook.cavityLeft,
    overflow: 'clip',
    perspective: '22cqw',
    perspectiveOrigin: '50% 50%',
    borderRadius: splitFlapLook.faceRadius,
    backgroundColor: splitFlapLook.cavityColor,
    boxShadow: splitFlapLook.cavityShadow,
  },
  compactCell: {
    isolation: 'isolate',
    '::before': {
      position: 'absolute',
      zIndex: 4,
      top: '50%',
      right: '0.08cqw',
      bottom: '0.08cqw',
      left: '0.08cqw',
      content: '',
      opacity: 'var(--compact-motion-shadow-opacity)',
      backgroundImage:
        'radial-gradient(ellipse 96% 20% at 47% 0%, rgba(0, 0, 0, 0.98), transparent 70%), linear-gradient(180deg, rgba(0, 0, 0, 0.62), transparent 39%)',
      transform: 'var(--compact-motion-shadow-transform)',
      transformOrigin: '50% 50%',
      pointerEvents: 'none',
    },
    '::after': {
      position: 'absolute',
      zIndex: 6,
      inset: 0,
      content: '',
      backgroundImage: 'var(--compact-bezel-background)',
      opacity: 'var(--compact-bezel-opacity)',
      pointerEvents: 'none',
    },
  },
  cellScene: {
    position: 'absolute',
    inset: 0,
    transformStyle: 'preserve-3d',
    pointerEvents: 'none',
  },
  cavityBackPlane: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    backgroundColor: '#030403',
    backgroundImage:
      'linear-gradient(180deg, #010201 0%, #070806 48%, #020302 100%), repeating-linear-gradient(180deg, transparent 0 0.24cqw, rgba(111, 113, 97, 0.1) 0.26cqw 0.3cqw)',
    boxShadow: '0 0.22cqw 0.44cqw rgba(0, 0, 0, 0.9) inset',
    pointerEvents: 'none',
  },
  cavityWall: {
    position: 'absolute',
    zIndex: 1,
    backgroundColor: '#10120f',
    pointerEvents: 'none',
  },
  cavityWallTop: {
    top: 0,
    right: 0,
    left: 0,
    backgroundImage: 'linear-gradient(180deg, #252822 0%, #080a08 100%)',
    transform: 'rotateX(-90deg)',
    transformOrigin: '50% 0%',
  },
  cavityWallRight: {
    top: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'linear-gradient(90deg, #050605 0%, #151712 100%)',
    transform: 'rotateY(-90deg)',
    transformOrigin: '100% 50%',
  },
  cavityWallBottom: {
    right: 0,
    bottom: 0,
    left: 0,
    backgroundImage: 'linear-gradient(180deg, #060706 0%, #1c1e19 100%)',
    transform: 'rotateX(90deg)',
    transformOrigin: '50% 100%',
  },
  cavityWallLeft: {
    top: 0,
    bottom: 0,
    left: 0,
    backgroundImage: 'linear-gradient(90deg, #1e211c 0%, #080908 100%)',
    transform: 'rotateY(90deg)',
    transformOrigin: '0% 50%',
  },
  faceLayer: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
  },
  outgoingLower: {
    zIndex: 2,
  },
  arrivingUpper: {
    zIndex: 3,
  },
  compactGlyphCarrier: {
    '::before': {
      position: 'absolute',
      zIndex: 4,
      top: 'var(--compact-glyph-top)',
      left: '50%',
      display: 'block',
      content: 'attr(data-glyph)',
      color: 'var(--split-flap-active-glyph-color, var(--compact-glyph-fallback-color, #e8e5d7))',
      fontFamily: splitFlapLook.glyphFontFamily,
      fontSize: 'var(--compact-glyph-font-size)',
      fontWeight: splitFlapLook.glyphFontWeight,
      letterSpacing: 'var(--compact-glyph-tracking)',
      lineHeight: '12.2cqw',
      marginLeft: 'var(--compact-glyph-margin-left)',
      opacity: 'var(--compact-glyph-opacity)',
      textAlign: 'center',
      textShadow:
        '0 0 0.05cqw color-mix(in srgb, var(--split-flap-active-glyph-color, var(--compact-glyph-fallback-color, #e8e5d7)) 6%, transparent)',
      transform: 'var(--compact-glyph-transform)',
      transformOrigin: '50% 50%',
      width: 'var(--compact-glyph-width, 10cqw)',
      pointerEvents: 'none',
    },
  },
  compactWideGlyphCarrier: {
    color: 'var(--split-flap-active-glyph-color, var(--compact-glyph-fallback-color, #e8e5d7))',
    fontFamily: splitFlapLook.glyphFontFamily,
    fontSize: 'var(--compact-glyph-font-size)',
    fontWeight: splitFlapLook.glyphFontWeight,
    lineHeight: '12.2cqw',
    opacity: 'var(--compact-glyph-opacity)',
    textShadow:
      '0 0 0.05cqw color-mix(in srgb, var(--split-flap-active-glyph-color, var(--compact-glyph-fallback-color, #e8e5d7)) 6%, transparent)',
    '::before': {
      display: 'none',
    },
  },
  compactStaticFace: {
    position: 'absolute',
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  compactStaticTop: {
    zIndex: 3,
    borderTopLeftRadius: splitFlapLook.faceRadius,
    borderTopRightRadius: splitFlapLook.faceRadius,
    opacity: 0,
    transformOrigin: '50% 100%',
  },
  compactStaticBottom: {
    zIndex: 2,
    top: '50%',
    borderBottomLeftRadius: splitFlapLook.faceRadius,
    borderBottomRightRadius: splitFlapLook.faceRadius,
    transformOrigin: '50% 0%',
  },
  compactMovingVane: {
    zIndex: 5,
    opacity: 0,
    willChange: 'transform',
  },
  compactMovingVaneFace: {
    overflow: 'hidden',
    borderRadius: splitFlapLook.faceRadius,
    backgroundColor: '#25261f',
    backgroundRepeat: 'no-repeat',
  },
  compactMovingStack: {
    position: 'absolute',
    zIndex: 3,
    inset: 0,
    backgroundRepeat: 'no-repeat',
    pointerEvents: 'none',
    willChange: 'transform',
  },
  movingVane: {
    position: 'absolute',
    zIndex: 4,
    inset: 0,
    transform: 'translate3d(0, 0, 0) rotateX(0deg)',
    transformOrigin: '50% 50%',
    transformStyle: 'preserve-3d',
    pointerEvents: 'none',
    willChange: 'transform',
  },
  movingVaneFace: {
    position: 'absolute',
    inset: 0,
    backfaceVisibility: 'hidden',
    pointerEvents: 'none',
  },
  movingVaneFront: {
    transform: 'rotateX(0deg)',
  },
  movingVaneBack: {
    transform: 'rotateX(180deg)',
  },
  movingVaneSpecular: {
    position: 'absolute',
    zIndex: 6,
    opacity: 'var(--split-flap-specular, 0)',
    borderRadius: '0.025cqw',
    pointerEvents: 'none',
  },
  movingVaneBackSpecular: {
    backgroundImage:
      'linear-gradient(102deg, transparent 0%, transparent 45%, rgba(185, 184, 169, 0.16) 48%, rgba(231, 229, 211, 0.32) 52%, rgba(171, 173, 160, 0.1) 56%, transparent 61%, transparent 100%)',
  },
  movingVaneEdge: {
    position: 'absolute',
    zIndex: 7,
    opacity: 0.72,
    backgroundColor: '#1d201d',
    backgroundImage:
      'linear-gradient(90deg, #080a08 0%, #30342f 22%, #777d76 42%, #2a2e2a 63%, #070807 100%)',
    boxShadow: '0 0 0 0.018cqw rgba(0, 0, 0, 0.92)',
    transform: 'rotateX(90deg)',
    transformOrigin: '50% 50%',
    pointerEvents: 'none',
  },
  movingVaneSide: {
    position: 'absolute',
    zIndex: 7,
    backgroundColor: '#111310',
    backgroundImage: 'linear-gradient(180deg, #252823 0%, #0a0c0a 48%, #1a1c18 100%)',
    boxShadow: '0 0 0 0.012cqw rgba(0, 0, 0, 0.82)',
    pointerEvents: 'none',
  },
  movingVaneSideLeft: {
    transform: 'rotateY(90deg)',
    transformOrigin: '50% 50%',
  },
  movingVaneSideRight: {
    transform: 'rotateY(-90deg)',
    transformOrigin: '50% 50%',
  },
  motionShadow: {
    position: 'absolute',
    zIndex: 3,
    right: '0.1cqw',
    left: '0.1cqw',
    opacity: 0,
    pointerEvents: 'none',
    transformOrigin: '50% 50%',
    willChange: 'opacity, transform',
  },
  lowerMotionShadow: {
    top: '50%',
    bottom: '0.1cqw',
    backgroundImage:
      'radial-gradient(ellipse 96% 20% at 47% 0%, rgba(0, 0, 0, 0.98), transparent 70%), linear-gradient(180deg, rgba(0, 0, 0, 0.62), transparent 39%)',
  },
  cassetteCover: {
    position: 'absolute',
    zIndex: 7,
    display: 'block',
    backgroundColor: 'transparent',
    pointerEvents: 'none',
  },
  cassetteCoverTop: {
    top: 0,
    right: 0,
    left: 0,
    height: splitFlapLook.cavityTop,
    backgroundImage: splitFlapLook.coverTopBackground,
    boxShadow: splitFlapLook.coverTopShadow,
  },
  cassetteCoverRight: {
    top: splitFlapLook.cavityTop,
    right: 0,
    bottom: splitFlapLook.cavityBottom,
    width: splitFlapLook.cavityRight,
    backgroundImage: splitFlapLook.coverRightBackground,
    boxShadow: splitFlapLook.coverRightShadow,
  },
  cassetteCoverBottom: {
    right: 0,
    bottom: 0,
    left: 0,
    height: splitFlapLook.cavityBottom,
    backgroundImage: splitFlapLook.coverBottomBackground,
    boxShadow: splitFlapLook.coverBottomShadow,
  },
  cassetteCoverLeft: {
    top: splitFlapLook.cavityTop,
    bottom: splitFlapLook.cavityBottom,
    left: 0,
    width: splitFlapLook.cavityLeft,
    backgroundImage: splitFlapLook.coverLeftBackground,
    boxShadow: splitFlapLook.coverLeftShadow,
  },
  face: {
    position: 'absolute',
    zIndex: 1,
    right: splitFlapLook.faceInsetX,
    left: splitFlapLook.faceInsetX,
    overflow: 'hidden',
    backgroundColor: splitFlapLook.bottomFaceColor,
    backfaceVisibility: 'hidden',
    boxShadow: splitFlapLook.topFaceShadow,
  },
  topFace: {
    zIndex: 3,
    top: splitFlapLook.faceInsetY,
    height: `calc(50% - ${splitFlapLook.faceInsetY})`,
    borderTopLeftRadius: splitFlapLook.faceRadius,
    borderTopRightRadius: splitFlapLook.faceRadius,
    backgroundColor: splitFlapLook.topFaceColor,
  },
  bottomFace: {
    zIndex: 2,
    top: '50%',
    borderBottomLeftRadius: splitFlapLook.faceRadius,
    borderBottomRightRadius: splitFlapLook.faceRadius,
    backgroundColor: splitFlapLook.bottomFaceColor,
  },
  glyph: {
    position: 'absolute',
    left: '50%',
    display: 'block',
    width: '10cqw',
    color: '#d9d2b5',
    fontFamily: splitFlapLook.glyphFontFamily,
    fontSize: splitFlapLook.glyphSize,
    fontWeight: splitFlapLook.glyphFontWeight,
    letterSpacing: splitFlapLook.glyphTracking,
    lineHeight: '12.2cqw',
    opacity: splitFlapLook.glyphOpacity,
    textAlign: 'center',
    textShadow: '0 0 0.05cqw rgba(226, 217, 181, 0.06)',
    transform: 'translateX(-50%) scaleX(0.62)',
    transformOrigin: '50% 50%',
  },
  wideGlyphCarrier: {
    display: 'grid',
    gridTemplateColumns: '42% 16% 42%',
  },
  wideGlyphPart: {
    display: 'block',
    gridRow: 1,
    textAlign: 'center',
    transform: 'var(--wide-glyph-transform)',
    transformOrigin: '50% 50%',
  },
  compactWideGlyphPart: {
    position: 'absolute',
    top: 'var(--compact-glyph-top)',
    width: '42%',
  },
  wideGlyphPartLeft: {
    left: 0,
    gridColumn: 1,
  },
  wideGlyphPartRight: {
    left: '58%',
    gridColumn: 3,
  },
  glyphHalf: {
    position: 'absolute',
    zIndex: 4,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  topGlyphHalf: {
    inset: '0 0 50%',
    maskImage:
      'linear-gradient(180deg, #000 0%, #000 calc(100% - 0.18cqw), rgba(0, 0, 0, 0.76) 100%)',
  },
  bottomGlyphHalf: {
    inset: 0,
    clipPath: 'inset(50% 0 0)',
    maskImage:
      'linear-gradient(180deg, rgba(0, 0, 0, 0.82) 50%, #000 calc(50% + 0.16cqw), #000 100%)',
  },
  movingGlyphHalf: {
    maskImage: 'none',
  },
  glyphFarLeft: {
    marginLeft: '-0.12cqw',
  },
  glyphLeft: {
    marginLeft: '-0.06cqw',
  },
  glyphCenter: {
    marginLeft: 0,
  },
  glyphSoftRight: {
    marginLeft: '0.04cqw',
  },
  glyphRight: {
    marginLeft: '0.08cqw',
  },
  seam: {
    position: 'absolute',
    zIndex: 5,
    top: '50%',
    right: '0.1cqw',
    left: '0.1cqw',
    height: '0.08cqw',
    backgroundColor: 'rgba(7, 8, 6, 0.55)',
    filter: 'blur(0.015cqw)',
    transform: 'translateY(-50%)',
  },
  upperSeamShadow: {
    position: 'absolute',
    zIndex: 3,
    right: '0.1cqw',
    left: '0.1cqw',
    height: '0.62cqw',
    pointerEvents: 'none',
  },
  lowerSeamShadow: {
    position: 'absolute',
    zIndex: 3,
    right: '0.1cqw',
    left: '0.1cqw',
    height: '0.48cqw',
    pointerEvents: 'none',
  },
  axle: {
    position: 'absolute',
    zIndex: 7,
    top: '50%',
    width: splitFlapLook.axleWidth,
    height: splitFlapLook.axleHeight,
    borderRadius: '42%',
    backgroundColor: '#0a0b08',
    backgroundImage: splitFlapLook.axleBackground,
    boxShadow: splitFlapLook.axleShadow,
    opacity: splitFlapLook.axleOpacity,
    transform: 'translate3d(0, -50%, 0.18cqw)',
    pointerEvents: 'none',
  },
  axleLeft: {
    left: '0.02cqw',
  },
  axleRight: {
    right: '0.02cqw',
  },
  compactWideHardware: {
    position: 'absolute',
    zIndex: 8,
    top: splitFlapLook.cavityTop,
    right: splitFlapLook.cavityRight,
    bottom: splitFlapLook.cavityBottom,
    left: splitFlapLook.cavityLeft,
    pointerEvents: 'none',
  },
  compactWideSeam: {
    position: 'absolute',
    zIndex: 5,
    top: '50%',
    right: '0.1cqw',
    left: '0.1cqw',
    height: 'var(--compact-seam-height)',
    backgroundImage:
      'linear-gradient(90deg, rgba(4 5 3 / calc(0.98 * var(--compact-seam-base-opacity))) 0%, rgba(9 10 7 / calc(0.94 * var(--compact-seam-base-opacity))) 38%, rgba(5 6 4 / var(--compact-seam-base-opacity)) 78%, rgba(3 4 3 / calc(0.97 * var(--compact-seam-base-opacity))) 100%)',
    transform: 'translateY(-50%)',
  },
  wideRetainer: {
    position: 'absolute',
    zIndex: 7,
    top: '50%',
    width: '0.36cqw',
    height: '4.6cqw',
    borderRadius: '28%',
    backgroundColor: '#0a0b08',
    backgroundImage: splitFlapLook.axleBackground,
    boxShadow: splitFlapLook.axleShadow,
    opacity: splitFlapLook.axleOpacity,
    transform: 'translate3d(-50%, -50%, 0.18cqw)',
    pointerEvents: 'none',
  },
  wideRetainerOuterLeft: {
    left: '0.28cqw',
  },
  wideRetainerInnerLeft: {
    left: '42%',
  },
  wideRetainerInnerRight: {
    left: '58%',
  },
  wideRetainerOuterRight: {
    left: 'calc(100% - 0.28cqw)',
  },
  spareLeafPack: {
    position: 'absolute',
    zIndex: 1,
    inset: 0,
    clipPath: 'inset(50% 0 0)',
    pointerEvents: 'none',
  },
  spareLeafPlate: {
    position: 'absolute',
    right: '0.06cqw',
    bottom: '0.18cqw',
    left: '0.06cqw',
    boxSizing: 'border-box',
    height: 'calc(50% - 0.18cqw)',
    borderBottomLeftRadius: '0.03cqw',
    borderBottomRightRadius: '0.03cqw',
    borderBottomWidth: '0.13cqw',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(3, 4, 2, 0.96)',
    backgroundColor: '#1a1b16',
    backgroundImage:
      'linear-gradient(180deg, #24251e 0%, #1a1b16 68%, #0b0c09 91%, #35362c 95.5%, #151610 98%, #080906 100%)',
    boxShadow:
      '0 0.045cqw 0.065cqw rgba(0, 0, 0, 0.62), 0 -0.2cqw 0 rgba(190, 182, 143, 0.18) inset',
    clipPath:
      'polygon(0.03cqw 0, calc(100% - 0.02cqw) 0, 100% 13%, calc(100% - 0.04cqw) 27%, 100% 42%, calc(100% - 0.03cqw) 58%, 100% 73%, calc(100% - 0.05cqw) 87%, calc(100% - 0.01cqw) 100%, 0.02cqw 100%, 0 86%, 0.04cqw 71%, 0 55%, 0.05cqw 39%, 0 24%, 0.03cqw 11%)',
    pointerEvents: 'none',
  },
  cassetteBezel: {
    position: 'absolute',
    zIndex: 6,
    inset: 0,
    backgroundImage:
      'linear-gradient(90deg, rgba(82, 83, 68, 0.5) 0, rgba(5, 6, 4, 0.96) 0.06cqw, rgba(0, 0, 0, 0.42) 0.14cqw, transparent 0.3cqw), linear-gradient(270deg, rgba(72, 73, 60, 0.44) 0, rgba(5, 6, 4, 0.94) 0.06cqw, rgba(0, 0, 0, 0.36) 0.14cqw, transparent 0.28cqw), linear-gradient(180deg, rgba(4, 5, 3, 0.78) 0, transparent 0.22cqw), linear-gradient(0deg, rgba(3, 4, 2, 0.88) 0, transparent 0.28cqw)',
    pointerEvents: 'none',
  },
})

export const glyphOffsets = [
  styles.glyphLeft,
  styles.glyphCenter,
  styles.glyphRight,
  styles.glyphFarLeft,
  styles.glyphCenter,
  styles.glyphSoftRight,
] as const
